### PR TITLE
Minor updates - styling, imports, requirements, .gitignore

### PR DESCRIPTION
**Pull request by Ekultek**
* `setup.py`
   - Minor styling updates, just reformatted the file to be to pep standards, also removed unused imports
* `test,py` 
   - Styling updates to pip standards
   - Removed unused import for `uuid`
   - Edited some variables because the aren't used
* `requirments.txt` these aren't always necessary but it's good to have. People would probably like to know that they need the `lazy` and `cffi` package to run this application.
* `.gitignore` pycharm creates a `.idea` directory that nobody likes, so I added it for you.

### CODE REVIEW

**Comment by ctubbsii** [comment]
@Ekultek Thank you for your contribution!

**Comment by Ekultek** [comment]
@ctubbsii welcome, anything specific you're looking to get edited in the C files? From what I can tell, they look pretty decently done

**Comment by ctubbsii** [comment]
Sorry, I'm not sure. I'm not the author or maintainer. Just helping out curating the GitHub account and wanted to toss out a "thanks" so contributors feels appreciated. :)

Maybe @NSA-LGDev2 has some future work in mind where somebody could contribute further? If they do, they might create a "TODO" issue at some point.

**Comment by Ekultek** [comment]
@ctubbsii okay cool, the `TODO` would be nice, that way people can see what needs to be done and what you're looking for other then blindly creating pull requests for stuff that we think you guys might want.

**Pull request merged**
